### ISSUE TITLE
Understand Usage & Internals

### ISSUE THREAD

**Issue by shahamit** [dekelev/kong-transparent-proxy#1]
I am looking for a forward proxy for our application that monitors (logs) outgoing third party api calls made by our application. I would like to understand if this transparent proxy plugin can serve that purpose.

If it does make kong to act as a forward proxy, kindly throw some light on 
1. How does it intercept the outgoing http api requests. Do I need to make code changes in our application for it to do so?
2. Would it log all third party api calls OR is there a config to specify the host names?

I would appreciate it if you could share some insight on this.

Thanks!

**Comment by dekelev** [comment]
Hi @shahamit, Thanks for your interest in this plugin. I built it for local development between NodeJS & K8s apps, but it is basically a standard HTTP transparent proxy, like the type that browsers can use.

1. You will need to set up your application with an HTTP proxy that has the Kong HTTP URL (and port 8000 by default) as its value

2. It is configured to log only with log_level=debug, but maybe we can change this to also log on log_level=info, what do you think?

**Comment by shahamit** [comment]
Thanks for the follow up.

> You will need to set up your application with an HTTP proxy that has the Kong HTTP URL (and port 8000 by default) as its value

What changes do I need in my (java based) application for the outgoing calls go through the proxy?

**Comment by dekelev** [comment]
I guess you can find more info about this here:
https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html
https://www.baeldung.com/java-connect-via-proxy-server
